site_name: Multi Ping
site_url: https://tiagocoutinho.github.io/multi-ping
site_description: Python ping library
site_author: Tiago Coutinho
copyright: "© 2024 Tiago Coutinho"

repo_url: https://github.com/tiagocoutinho/multi-ping
repo_name: tiagocoutinho/multi-ping

# disable editing code link
edit_uri: ''

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: spacy
            members_order: source
            merge_init_into_class: true
            separate_signature: false
            show_source: false
            show_bases: true
            show_root_heading: true
            show_signature_annotations: true
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            unwrap_annotated: true
  - search

theme:
  name: material
  language: en
  palette:
    primary: blue grey
    accent: light blue
  font:
    text: Roboto
    code: 'Roboto Mono'
  logo: img/logo-128x128.png
  favicon: img/favicon.ico
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs

extra_css:
  - css/termynal.css

extra_javascript:
  - js/termynal.js

markdown_extensions:
  meta: null
  admonition: null
  codehilite: null
  toc:
    permalink: true
  pymdownx.details: null
  pymdownx.inlinehilite: null
  pymdownx.superfences: null
  pymdownx.tabbed:
    alternate_style: true

nav:
  - Multiping: index.md
  - User guide: user_guide.md
  - API Reference: api.md
  - Developers corner: develop.md
